# Generated by Django 6.1 on 2026-09-21 05:55

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_alter_product_image_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/ecom_default.jpeg', upload_to=myapp.models.Product.product_image_path),
        ),
    ]
