# Generated by Django 6.1 on 2026-09-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='socket',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
