# Generated by Django 6.1 on 2026-09-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_memory_type_product_socket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('processor', 'Procesador'), ('motherboard', 'Placa Madre'), ('ram', 'RAM')], max_length=20, null=True),
        ),
    ]
